name: Docker push container at org level (GITHUB_TOKEN)
on: workflow_dispatch

permissions:
 packages: write
 
env:
 pkg: "drupal"

jobs:
 all:
  runs-on: self-hosted
  
  steps:
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: Build the Docker image
     run: docker pull $pkg:latest
   - name: Tag the Docker image
     run: docker tag $pkg:latest ghcr.io/cppkg/$pkg:latest
   - name: Push the Docker image to the registry
     run: docker push ghcr.io/cppkg/$pkg:latest
